/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.handong.csee.java.ingeritance;
public class Animal {
	public void whoAmI() {
		//Animal dog = new Dog(); // Polymorphism: The 'dog' variable of type Animal can refer to an instance of Dog.
		//Animal monkey = new Monkey(); // Polymorphism: The 'monkey' variable of type Animal can refer to an instance of Monkey.
		
		//dog.whoAmI(); // Resulting message: "I am a dog." (Dynamic method dispatch invokes the overridden method in Dog class.)
		//monkey.whoAmI(); // Resulting message: "I am a monkey." (Dynamic method dispatch invokes the overridden method in Monkey class.)
	}
}
